# Database config
spring.datasource.url=jdbc:mysql://localhost:3306/admin_flight
spring.datasource.username=root
spring.datasource.password=Welcome@123

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

source.required=Source cannot be empty
destination.required=Destination cannot be empty
city.invalid=City name must contain only alphabets
travel.date.required=Travel date is required
travel.date.invalid=Travel date cannot be in the past
travellers.required=Number of travellers is required
travellers.min=At least one traveller is required
