# Database config
spring.datasource.url=jdbc:mysql://localhost:3306/admin_flight
spring.datasource.username=root
spring.datasource.password=Welcome@123

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.messages.basename=application
source.required=Source name is invalid
destination.required=Destination name is invalid
city.invalid=City name is invalid
travel.date.required=Travel date is required
travel.date.invalid=Travel date cannot be in the past
travellers.required=Number of travellers is required
travellers.min=At least one traveller is required
airline.name.required=Airline name is invalid
airline.name.invalid=Airline name must contain only alphabets
contact.required=Contact number cannot be empty
contact.invalid=Contact number must be exactly 10 digits
headquarters.required=Headquarters cannot be empty
flight.number.required=Flight number is required
flight.number.invalid=Flight number must be in format like AI203 or EK507
aircraft.type.required=Aircraft type is required
aircraft.type.invalid=Aircraft type may contain only letters, numbers, spaces, and hyphens
